
//! Autogenerated weights for `pallet_sugondat_blobs`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-11-24, STEPS: `10`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `gab`, CPU: `Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/sugondat-node
// benchmark
// pallet
// --dev
// --pallet
// pallet_sugondat_blobs
// --extrinsic
// *
// --steps
// 10
// --repeat
// 20
// --template
// sugondat-chain/pallets/blobs/src/frame-weight-template.hbs
// --output
// sugondat-chain/pallets/blobs/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_sugondat_blobs`.
pub trait WeightInfo {
	fn submit_blob(x: u32, y: u32, ) -> Weight;
}

/// Weights for `pallet_sugondat_blobs` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Blobs::TotalBlobsSize` (r:1 w:1)
	/// Proof: `Blobs::TotalBlobsSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Blobs::BlobList` (r:1 w:1)
	/// Proof: `Blobs::BlobList` (`max_values`: Some(1), `max_size`: Some(7372804), added: 7373299, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[0, 102399]`.
	/// The range of component `y` is `[1, 102400]`.
	fn submit_blob(x: u32, _y: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `60 + x * (72 ±0)`
		//  Estimated: `7374289`
		// Minimum execution time: 538_192_000 picoseconds.
		Weight::from_parts(5_925_405_895, 7374289)
			// Standard Error: 7_234
			.saturating_add(Weight::from_parts(209_215, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Blobs::TotalBlobsSize` (r:1 w:1)
	/// Proof: `Blobs::TotalBlobsSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Blobs::BlobList` (r:1 w:1)
	/// Proof: `Blobs::BlobList` (`max_values`: Some(1), `max_size`: Some(7372804), added: 7373299, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[0, 102399]`.
	/// The range of component `y` is `[1, 102400]`.
	fn submit_blob(x: u32, _y: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `60 + x * (72 ±0)`
		//  Estimated: `7374289`
		// Minimum execution time: 538_192_000 picoseconds.
		Weight::from_parts(5_925_405_895, 7374289)
			// Standard Error: 7_234
			.saturating_add(Weight::from_parts(209_215, 0).saturating_mul(x.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
