name: sugondat

services:
  zombienet:
    image: ghcr.io/pepyakin/blobs-demostand:latest
    # Mount /zombienet as tmpfs so as to avoid zombienet prompting if it should ignore existing 
    # directory.
    tmpfs: /zombienet
  shim:
    image: ghcr.io/pepyakin/blobs-shim:latest
    depends_on:
      zombienet:
        condition: service_healthy
    environment:
      - RUST_LOG=sugondat=trace
    command: ["serve", "-p", "10995", "--node-url=ws://zombienet:9988", "--submit-dev-alice"]
  gm:
    image: ghcr.io/pepyakin/blobs-demo-gm:latest
  sov:
    image: ghcr.io/pepyakin/blobs-demo-sov:latest
