# TODO: Do I need an explicit declaration of networks?

name: sugondat

services:
  zombienet:
    image: ghcr.io/pepyakin/blobs-demostand:latest
    networks:
      - local
  shim:
    image: ghcr.io/pepyakin/blobs-shim:latest
    depends_on:
      zombienet:
        condition: service_healthy
    networks:
      - local
    environment:
      - RUST_LOG=sugondat=trace
    command: ["serve", "-p", "10995", "--node-url=ws://zombienet:9988"]
  gm:
    image: ghcr.io/pepyakin/blobs-demo-gm:latest
    networks: 
      - local
  sov:
    image: ghcr.io/pepyakin/blobs-demo-sov:latest
    networks:
      - local

networks:
  local: {}
