name: buildbase

on: 
  workflow_dispatch: {}
  schedule:
    - cron: '0 6 * * *' # run the build at 6:00 UTC POSIX time

# The jobs below are almost identical. Basically they build the following docker images from
# the corresponding build targets (/stages) of the buildbase dockerfile:
#
# - blobs-buildbase-sugondat-node-release
# - blobs-buildbase-sugondat-workspace-check
# - blobs-buildbase-sugondat-workspace-test
jobs:
    buildbase-sugondat-node-release:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./ci/buildbase-sugondat.Dockerfile
            platforms: linux/amd64
            push: true
            target: sugondat-node-release
            tags: |
              ghcr.io/pepyakin/blobs-buildbase-sugondat-node-release:latest
    buildbase-sugondat-workspace-check:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./ci/buildbase-sugondat.Dockerfile
            platforms: linux/amd64
            push: true
            target: sugondat-workspace-check
            tags: |
              ghcr.io/pepyakin/blobs-buildbase-sugondat-workspace-check:latest
    buildbase-sugondat-workspace-test:
      runs-on: ubuntu-latest
      steps:
        - name: Free Disk Space (Ubuntu)
          uses: jlumbroso/free-disk-space@main
          with:
            android: true
            dotnet: true
            haskell: true
            large-packages: true
            docker-images: true
            swap-storage: true
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./ci/buildbase-sugondat.Dockerfile
            platforms: linux/amd64
            push: true
            target: sugondat-workspace-test
            tags: |
              ghcr.io/pepyakin/blobs-buildbase-sugondat-workspace-test:latest
# TODO: repeat for others
