name: buildbase

# TODO: add cron nightly
on: workflow_dispatch

jobs:
    buildbase-sugondat-node-release:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./ci/buildbase-sugondat.Dockerfile
            platforms: linux/amd64
            push: true
            target: sugondat-node-release
            tags: |
              ghcr.io/pepyakin/blobs-buildbase-sugondat-node-release:latest
# TODO: repeat for others
