name: ci

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pepyakin/blobs-buildbase-sugondat-workspace-check:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo
      - name: Move
        run: rm -rf /sugondat && mv repo /sugondat
      - name: Check
        working-directory: /sugondat
        shell: bash
        run: su -c "/cargo/bin/cargo +nightly-2023-10-16 check --workspace"
  test:
    name: test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pepyakin/blobs-buildbase-sugondat-workspace-test:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo
      - name: Move
        run: rm -rf /sugondat && mv repo /sugondat
      - name: Check
        working-directory: /sugondat
        shell: bash
        run: su -c "/cargo/bin/cargo +nightly-2023-10-16 test --workspace"
